In [2]:
# test code
### gym version=0.26.2
import gym

In [8]:
### CartPole
env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset(seed=42)

for _ in range(10):
    for t in range(1000):
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated:
            end = "terminated"
            if truncated : end="truncated"
            print("Episode finished after {} timesteps".format(t+1), end)
            observation, info = env.reset()
            break

env.close()

Episode finished after 20 timesteps terminated
Episode finished after 31 timesteps terminated
Episode finished after 13 timesteps terminated
Episode finished after 39 timesteps terminated
Episode finished after 14 timesteps terminated
Episode finished after 19 timesteps terminated
Episode finished after 30 timesteps terminated
Episode finished after 16 timesteps terminated
Episode finished after 15 timesteps terminated
Episode finished after 17 timesteps terminated


In [6]:
### LunarLander
env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset(seed=123, options={})

done=False
while not done:
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

    done = terminated or truncated

env.close()

KeyboardInterrupt: 

In [7]:
### driving car : continous action  3 type!!
env = gym.make("CarRacing-v2", render_mode="human")
observation, info = env.reset(seed=410, options={})

done=False
while not done:
    action = env.action_space.sample()
    print(action, type(action))
    observation, reward, terminated, truncated, info = env.step(action)

    done = terminated or truncated

env.close()

[-0.4770237   0.24445486  0.621692  ] <class 'numpy.ndarray'>
[0.20970938 0.15607521 0.9592784 ] <class 'numpy.ndarray'>
[-0.08135748  0.84234023  0.49249047] <class 'numpy.ndarray'>
[0.16736835 0.04377573 0.56597036] <class 'numpy.ndarray'>
[-0.9415608   0.38711357  0.9506455 ] <class 'numpy.ndarray'>
[-0.4316775  0.9716559  0.1611044] <class 'numpy.ndarray'>
[0.42712107 0.20172268 0.73884624] <class 'numpy.ndarray'>
[-0.64382434  0.26028988  0.5107284 ] <class 'numpy.ndarray'>
[0.5050721  0.4995434  0.33686256] <class 'numpy.ndarray'>
[0.250068   0.29803655 0.13786602] <class 'numpy.ndarray'>
[0.03819606 0.55760574 0.67638636] <class 'numpy.ndarray'>
[-0.642026    0.02056907  0.16068825] <class 'numpy.ndarray'>
[0.39407718 0.06322233 0.40939617] <class 'numpy.ndarray'>
[-0.35778543  0.09577371  0.37470368] <class 'numpy.ndarray'>
[0.42612246 0.0477208  0.6474679 ] <class 'numpy.ndarray'>
[0.3675457  0.94984525 0.61955917] <class 'numpy.ndarray'>
[0.27185354 0.740345   0.02744307] <cl

KeyboardInterrupt: 